#ifndef MONOPOLY_COMMON
#define MONOPOLY_COMMON

#define BANK_MONEY_AMOUNT 15140
#define PLAYER_MONEY_START ( 2*500 + 2*100 + 2*50 + 6*20 + 5*10 + 5*5 + 5*1 )

typedef enum
{
SQUARE_INVALID = 0,
SQUARE_START,
SQUARE_COMMON_LAND,
SQUARE_RANDOM,
SQUARE_INCOME_TAX,
SQUARE_FREE_PARKING,
SQUARE_GO_TO_JAIL,
SQUARE_JAIL,
SQUARE_PROPERTY,
SQUARE_STATION,
SQUARE_UTILITY
} SQUARE_E;

typedef enum
{
TOKEN_INVALID = 0,
TOKEN_TERRIER,
TOKEN_BATTLESHIP,
TOKEN_AUTOMOBILE,
TOKEN_TOP_HAT,
TOKEN_THIMBLE,
TOKEN_SHOE,
TOKEN_WHEELBARROW,
TOKEN_IRON
} TOKEN_E;

typedef struct
{
uint8_t index;
SQUARE_E type;
void* data;
} SQUARE_T;

typedef struct
{
TOKEN_E token;
char* name;
int32_t account_balance; /* Check this */
SQUARE_T* current_place;
} PLAYER_T;

#endif /* #ifndef MONOPOLY_COMMON */
